### ISSUE TITLE
Robotology's SVN server down

### ISSUE THREAD

**Issue by jeljaik** [robotology/QA#120]
Can't access the robotology svn server

I checked online and this is what I see

![image](https://cloud.githubusercontent.com/assets/5030039/16042218/fd7d7b56-3239-11e6-8269-81de01f04e2a.png)

News on this?

**Comment by mbrunettini** [comment]
We had an issue during the weekend due tp the domain migration.
But it has been confirmed to work now.
Please check again.

**Comment by jeljaik** [comment]
Thanks!
