### ISSUE TITLE
Work in progress pull requests

### ISSUE THREAD

**Issue by drdanz** [robotology/QA#121]
It's happening more and more frequently that people (myself included) open pull requests for work in progress branches, for different reasons (testing if something breaks some build, requesting early feedback, etc).
I think this is a good thing, but sometimes it is not easy to spot whether a pull request is a real one, or a work in progress.

I suggest to follow [this workflow in gitlab](http://docs.gitlab.com/ce/workflow/wip_merge_requests.html), i.e. add `WIP:` or `[WIP]` at the beginning of the title of a "work in progress pull request" and remove it when the pull request is ready to be merged.
Even if this feature is not supported by github (in gitlab the merge button is disabled for this kind of merge requests), it will avoid accidental merges.

What do you think?

**Comment by pattacini** [comment]
I fully agree.
Nice suggestion.

**Comment by lornat75** [comment]
+1

**Comment by barbalberto** [comment]
We could also define WIP as a label to make it more visible

**Comment by drdanz** [comment]
@barbalberto We already have a "Status: In Progress" label, we can use that, I think...

**Comment by pattacini** [comment]
We could put this info in Yarp here: [**`CONTRIBUTING.md`**](https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md)

**Comment by vtikha** [comment]
Excellent!

Sent from my phone

On 17 Jun 2016, at 13:56, Daniele E. Domenichelli <notifications@github.com<mailto:notifications@github.com>> wrote:


It's happening more and more frequently that people (myself included) open pull requests for work in progress branches, for different reasons (testing if something breaks some build, requesting early feedback, etc).
I think this is a good thing, but sometimes it is not easy to spot whether a pull request is a real one, or a work in progress.

I suggest to follow this workflow in gitlab<http://docs.gitlab.com/ce/workflow/wip_merge_requests.html>, i.e. add WIP: or [WIP] at the beginning of the title of a "work in progress pull request" and remove it when the pull request is ready to be merged.
Even if this feature is not supported by github (in gitlab the merge button is disabled for this kind of merge requests), it will avoid accidental merges.

What do you think?

**Comment by randaz81** [comment]
+1
