### ISSUE TITLE
Confirming skin version number of our iCub

### ISSUE THREAD

**Issue by gsaponaro** [robotology/QA#174]
Hi, having read [here](http://wiki.icub.org/wiki/Tactile_sensors_(aka_Skin)) that there exist different versions of the iCub skin, we'd like to know which particular type is mounted on `iCubLisboa01`. For reference, this skin was installed during summer 2014.

/cc @randaz81 @maggia80 @vicentepedro https://github.com/robotology/QA/issues/39

**Comment by pattacini** [comment]
cc @robotology/icub-support-team

**Comment by pattacini** [comment]
Issue moved to [robotology/icub-support #344](https://github.com/robotology/icub-support/issues/344) via [**ZenHub**](https://www.zenhub.com/)
