### ISSUE TITLE
Problems about mono-directional communication (yarp -> ROS)

### ISSUE THREAD

**Issue by randaz81** [robotology/QA#182]
This is a tricky issue: a yarp machine (A) is able to subscribe to a ros topic and receive data correctly sent by a ros machine (B). But the data that (A) publishes on a ros topic are not received by the ROS machine (B). (*)

These are the things to check when this issue is observed:
* check that yarp server has been started with the `--ros` option
* check the existence of the` /ros` port with a `yarp name list` command. Be extremely careful when working with a wireless network:  if you use the `yarp clean --timeout xx.xx` there exists the risk to remove the /ros port if your system is affected by delay issues! See also: https://github.com/robotology/QA/issues/181
* Use the `yarp plugin --all` command to check  that the following yarp carrier plugins `rossrv, tcpros, xmlrpc` are compiled and can be found by the system. If they are not compiled, check if they are enabled in yarp cmake (`ENABLE_yarpcar_XXX` flags). If they are compiled but not found, check the `$YARP_DATA_DIRS` environment variable.
* Check the firewall settings.
* **_This is a very common source of problems and most likely the cause of the issue that you are experiencing now_**. Check the `/etc/hosts` on all the machines of your setup. Verify that all the machines are registered with their correct hostnames and ip addresses. If change an entry in this file, it's recommended to restart roscore and yarpserver. (**)
On windows the host names are stored in the file: `C:\Windows\System32\drivers\etc\hosts`

PS:
(*) indeed `rqt` tool shows that there are not connections from A to B.
(**) it may be possible that this behavior is caused by a bug in either yarpserver or roscore. Currently under investigation.

**Comment by barbalberto** [comment]
Can you please add more detail about this issue?

**Comment by pattacini** [comment]
@randaz81 I'm starting considering this issue an attempt to pollute the system 😉 
Something that will make you lose 💯 **robot-chlorian** per day. Watch out 😃 

But since you're a master and you helped us a lot these days I can close an eye, tonight...
