### ISSUE TITLE
Issue in downloading the virtual machine

### ISSUE THREAD

**Issue by LCaranzi** [robotology/QA#193]
Dear all,

I had troubles in downloading the VM. I managed to connect to the server (i.e. `ftp.iit.it`), but I do not have access to the subdirectory of the server, thus I cannot download the file `iCub_Ubuntu_16.04_x64.zip`.

The error message is **"Failed to retrieve directory listing"** as it can be seen in the image below.

Can someone help me?
Many thanks.

![directoryerror](https://cloud.githubusercontent.com/assets/26228175/23619470/04249130-0294-11e7-9fec-8b57e78cf497.jpg)

**Comment by pattacini** [comment]
Hi @mbrunettini 
Just for your reference, I've tried to download the VM via FileZilla and I was successful.

Could you help @LCaranzi?

**Comment by mbrunettini** [comment]
You must use the FTPS protocol (port 990), it seems that you connected using the default FTP port.
Ref [the following instructions](https://github.com/vvv-school/vvv17/wiki/Before%20arriving%20at%20VVV)

**Comment by LCaranzi** [comment]
Ok thanks, it worked!
