### ISSUE TITLE
ENABLE_yarpcar_bayer_carrier, set to ON

### ISSUE THREAD

**Issue by pedrombmachado** [robotology/QA#196]
Hi all,
   I am compiling the yarp and I following all the steps described in [icub-wiki](http://wiki.icub.org/wiki/Linux:Installation_from_sources) and [yarp-wiki](http://www.yarp.it/install_yarp_linux.html).
After this step:
CREATE_OPTIONAL_CARRIERS, set to ON 
I should be able to do
 **_ENABLE_yarpcar_bayer_carrier, set to ON_**
however the closest thing to this is:
ENABLE_yarpcar_bayer
Is this the equivalent thing? If so it is probably better to update the wiki.
Best wishes
Pedro

**Comment by pattacini** [comment]
Issue moved to [robotology/yarp #1126](https://github.com/robotology/yarp/issues/1126) via [**ZenHub**](https://www.zenhub.com/)
