### ISSUE TITLE
Is it possible to use the iCub arm without the hand? 

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/QA#213]
I am interested in using the robot arm without the hand. In practice I may need to use the shoulder and the elbow even if the hand have some problems at startup. Is it possible? What is the cleanest way to do so?

@DanielePucci  @pi-q @gabrielenava  @traversaro @randaz81

**Comment by S-Dafarra** [comment]
Actually I have found a method, but I 'm not sure it is the cleanest one. I'm going to describe it in a second (WIP)

**Comment by DanielePucci** [comment]
👍
