### ISSUE TITLE
Dragonfly Parameters documentation not available

### ISSUE THREAD

**Issue by pedrombmachado** [robotology/QA#214]
Dear all,
   For some reason the link http://eris.liralab.it/iCub/main/dox/html/group__icub__dragonfly2.html is not working. The link is suggested by the wiki http://wiki.icub.org/wiki/Dragonfly_Parameters.

**Comment by pattacini** [comment]
Hi @pedrombmachado 

Some time ago we migrated our infrastructure to http://wiki.icub.org.

Therefore, try this out: http://wiki.icub.org/iCub/main/dox/html/group__icub__dragonfly2.html.

I've updated the wiki accordingly.

**Comment by pedrombmachado** [comment]
Hi @pattacini ,
  It works. Many thanks.

**Comment by frank-foerster** [comment]
Hi (@pattacini ?), with a bit less than two years delay: the above website is offline again.
Could someone with the powers to do so, bring it back online again? 
Many thanks.

**Comment by traversaro** [comment]
Sorry for the trouble @frank-foerster , apparently the docs have changed the URL again, the documentation you are searching for should be available at http://www.icub.org/software_documentation/group__icub__dragonfly2.html .

**Comment by frank-foerster** [comment]
Great, thanks! By the looks of it the cameras can't do `native' black & white though, so I'll have to pump colour images through the network :(. 

Thanks again.
