### ISSUE TITLE
simulated icub on gazebo drifts when using Gaze controller

### ISSUE THREAD

**Issue by valeriosperati** [robotology/QA#242]
Hi, I have a code that initialises the gaze controller on simulated icub and, on a keypress event, directs the gaze on a fixed point using lookAtMonoPixel() function.
It works as expected with icub_SIM but fails using gazebo: the head robot immediately drifts after the initialisation of gaze controller

[video example](https://drive.google.com/open?id=0B7eFeb2P2Ie7bUV6NVFGNUlrb00)

 ```c++
    PolyDriver m_clientGaze;
    Property option_gaze;
    option_gaze.put("device","gazecontrollerclient");
    option_gaze.put("remote","/iKinGazeCtrl");
    option_gaze.put("local","/client/gaze");
    
    if(!m_clientGaze.open(option_gaze))
    {
	cout<<"\n[FATAL], problems in opening gaze controller...\n\t";
	cout<<"Is iKinGazeController running?...\n\n";
        std::string exit(0);
    }
    
    if(m_clientGaze.isValid())
    {
	m_clientGaze.view(iGaze);
    }else
    {
	cout<<"\n[FATAL], problems in viewing gaze controller...\n";
        std::string exit(0);
    }
    
    iGaze->setNeckTrajTime(0.8);
    iGaze->setEyesTrajTime(0.4);
    
    // put the gaze in tracking mode, so that
    // when the torso moves, the gaze controller 
    // will compensate for it
    iGaze->setTrackingMode(true);
    iGaze->setStabilizationMode(true);
```

iKinGazeCtrl is launched with parameters:

`iKinGazeCtrl --robot icubSim --from configSim.ini`

Gazebo is launched  with parameters:

`gazebo setupV0.sdf`

where setupV0.sdf is my starting configuration running  icub_with_hands and the worldInterface plugin:

```xml
<?xml version='1.0'?>
<sdf version='1.4'>
  <world name="my_world">

    <!-- Light -->
    <include>
      <uri>model://sun</uri>
    </include>

    <!-- Ground Plane -->
    <include>
      <uri>model://ground_plane</uri>
    </include>

   <!-- icub  and worldinterface plugin -->
   <model name="iCub_with_hands">
   	<include>
	    <uri>model://icub_with_hands</uri>
    	</include>
        <plugin name="world_interface" filename="libgazebo_yarp_worldinterface.so">
           <yarpConfigurationFile>model://worldInterface/conf/worldInterface.ini</yarpConfigurationFile>
        </plugin>
   </model>
</world>
</sdf>
```

The standard output of gazebo is the following:

[output.txt](https://github.com/robotology/QA/files/1135701/output.txt)

Thanks for help,
Valerio

**Comment by pattacini** [comment]
@valeriosperati I'm afraid that what you've seen is very much related to a number of open issues on https://github.com/robotology/icub-gazebo/issues that stem from the fact that `icub-gazebo` still need quite a lot of tuning of the low-level PID control layer.

See for example https://github.com/robotology/icub-gazebo/issues/38

Therefore, if you don't mind, I'd rather move this issue therein.

**Comment by valeriosperati** [comment]
Yea, sure!

**Comment by pattacini** [comment]
Issue moved to [robotology/icub-gazebo #61](https://github.com/robotology/icub-gazebo/issues/61) via [**ZenHub**](https://www.zenhub.com/)
