### ISSUE TITLE
iCub falls face down

### ISSUE THREAD

**Issue by pattacini** [robotology/QA#282]
@atabakd wrote:

>I have been trying to get this demo to work again, but I cannot remember which iCub model we were using. It works if I use "iCubGazeboV2_5 fixed" but iCub falls on the ground if I use "iCubGazeboV2_5 standing".
I am not sure if this was the expected behavior:thinking: 
Cheers,

**Comment by atabakd** [comment]
Thanks for moving it to the right place @pattacini. I just wanted to point that I was referring to the tutorial on impedance control.

**Comment by pattacini** [comment]
Sorry, my mistake then, I thought it was opened into vvv-school/vvv-school.github.io repo.
Issue restored in the original place.
