### ISSUE TITLE
Calibrating the little fingers after re-wiring

### ISSUE THREAD

**Issue by tasbolat1** [robotology/QA#286]
Hello, everyone!

I’ve recently changed a tendon wire. However, cannot able to re-calibration of it. What’s the fast and correct way of doing so?

**Comment by pattacini** [comment]
Hi @tasbolat1 
For hardware-wise issues, it's preferable to post on https://github.com/robotology/icub-support.
Thus, I'll redirect this port therein.

**Comment by pattacini** [comment]
Issue moved to [robotology/icub-support #632](https://github.com/robotology/icub-support/issues/632) via [**ZenHub**](https://www.zenhub.com/)
