### ISSUE TITLE
Can I cross-reference an issue from a different repository (i.e. in robotology)?

### ISSUE THREAD

**Issue by lornat75** [robotology/QA#3]

**Comment by lornat75** [comment]
Yes, you can include the name of the repository before the name, i.e.

This is dealt with in robotology/<repository-name>#<issue_number>

**Comment by traversaro** [comment]
Trick that saves some time, copy pasting directly the url of the issue result rendered in the same way, for example `https://github.com/robotology/codyco-superbuild/issues/43` becomes https://github.com/robotology/codyco-superbuild/issues/43 .

**Comment by rbonghi** [comment]
This is a good guide to understand principal feature about MarkDown
https://guides.github.com/features/mastering-markdown/

About **GitHub Flavored Markdown**
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
