### ISSUE TITLE
libgfortran error Cartesian Controller

### ISSUE THREAD

**Issue by robertorovella91** [robotology/QA#307]
Hi everyone, i try to use ICub with cartesian controller but when i run  " iKinCartesianSolver --context simCartesianControl --part right_arm" after "yarprobotinterface --context simCartesianControl " the following error occur:
" iKinCartesianSolver: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory "
How can i solve ? 
Thanks in advance.

**Comment by pattacini** [comment]
Self-closing issues are those we like the most 😉
