### ISSUE TITLE
Yarp installation error

### ISSUE THREAD

**Issue by Akashleena** [robotology/QA#418]
I do have YCMConfig.cmake.in in this path /home/aleena/icubLearningTrajectories/icub/software/src/ycm/YCMConfig.cmake.in. I have yarp in this path /home/aleena/icubLearningTrajectories/icub/software/src/yarp . When I am trying to cmake in yarp I get this error

Could not find a package configuration file provided by "YCM" (requested
version 0.11.0) with any of the following names:

YCMConfig.cmake
ycm-config.cmake

Add the installation prefix of "YCM" to CMAKE_PREFIX_PATH or set "YCM_DIR"
to a directory containing one of the above files. If "YCM" provides a
separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

How do I resolve this error?

**Comment by pattacini** [comment]
Closing, feel free to open it up again if needed.
