### ISSUE TITLE
AttributeError: module 'yarp' has no attribute 'Network'

### ISSUE THREAD

**Issue by zmd302** [robotology/QA#419]
Hi,
I am working on windows 10 and used Link ( http://wiki.icub.org/wiki/Check_your_installation ) to install icub  when i check installation, simulator is shown. But when I tried to control icub by python and initialize the yarp by
yarp.Network.init()
 it gives the following error.
AttributeError: module 'yarp' has no attribute 'Network'
Can anyone please tell me what is wrong with it? i also set the environment variables as specified on the installation guide and reinstalled yarp.
Thanks
@traversaro 
@drdanz

**Comment by pattacini** [comment]
A quite old issue; hopefully, the OP came up with a good solution.
