### ISSUE TITLE
 🚀 Distro 2020.05.patch-01 Released

### ISSUE THREAD

**Issue by Nicogene** [robotology/QA#425]
Hi @robotology/everyone 👋 

We're happy to announce that our latest iCub software distro **2020.05.patch-01** is now available.

To download the source code with the correct tags, check out our up-to-date [Software Versioning Table](https://wiki.icub.org/wiki/Software_Versioning_Table).

⚠️ This distro impacts only on `icub-firmware` and `icub-firmware-build` repositories.

This patch distro has been released after we spotted (and then fixed) a bug in the firmware of the bootloader of some CAN boards (`strain2`, `mtb4`, `rfe`, `psc`) released in the distro `2020.05` (#404).

This bug affects the bootloader making impossible a firmware update of the applications of those board. 

Like the feature-based releases, patches are shipped only in terms of tags/branches.

**Comment by DanielePucci** [comment]
CC @robotology/iit-dynamic-interaction-control
