### ISSUE TITLE
icubosaka01: how to reset up on icubsrv ?

### ISSUE THREAD

**Issue by YANGGANG1971** [robotology/QA#434]
I ran into [a login loop issue](https://github.com/robotology/icub-tech-support/issues/983). Now I am considering whether I need to reinstall all software on icubsrv. Is it complicated? Could you give me some tutorials?

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

It's unfortunate that you got stuck in this problem.
In the next days, @mbrunettini will give you a walkthrough guide to attempt to get around this problem.

**Comment by YANGGANG1971** [comment]
Thanks, @pattacini @mbrunettini

**Comment by YANGGANG1971** [comment]
We have fixed the login issue. But if possible, we still intend to learn how to reset up icubsrv in case, also for backup.

**Comment by pattacini** [comment]
@YANGGANG1971 you asked the same thing twice in two different places.
Closing here.
