### ISSUE TITLE
wholeBodyDynamicsTree calibStandingRightFoot calibrates for left_foot

### ISSUE THREAD

**Issue by hu-yue** [robotology/QA#69]
Hi,
I wanted to calibrate the robot standing on the right leg. However, when I did `calibStandingRightFoot` in `/wholeBodyDynamics/rpc:i` it seems to have calibrated for the left foot instead, since the force is shown to be below the left foot (which is in the air) instead of the right foot.

![icub_gui](http://orb.iwr.uni-heidelberg.de/ftp/icub_screenshots/icub_gui_calib.png)

cc @traversaro @DanielePucci

**Comment by hu-yue** [comment]
Ok sorry I have to take a moment for this, I was wrong on the foot issue.

**Comment by DanielePucci** [comment]
:)

**Comment by iron76** [comment]
😂

**Comment by hu-yue** [comment]
This gui problem is confusing me =/
