### ISSUE TITLE
Right wrist is stuck

### ISSUE THREAD

**Issue by kt10aan** [robotology/QA#7]
Hi,

The right wrist of our iCub  (Hertfordshire01) is stuck. I mean that it doesn't move at all, even with no power, when the robot is off (the movements corresponding to joints 5 and 6 in the right arm).

The last thing I was doing was running some pretty stock stuff in the ARE. Then, when I turned it off, I noticed that in the parking position the wrist was still stiff.

The yarp/icub software is a few days old. The firmware is at v80.

RobotmotorGui reports the joints as operational (however, moving the slider for joints 5 and 6 doesn't make any movement.

I have rebooted the robot completely a few times.

The log is here (taken from the YarpLogger).
https://dl.dropboxusercontent.com/u/22756225/log_pc104_robotInterface_3361

Some errors that are showing are during the shutdown procedure, and not during the startup, and they are there forever :)

**Comment by pattacini** [comment]
@kt10aan, for the time being it would be still better to forward such issues to mechies - since it seems the problem regards the mechanics - thus relying on icub-support@icub.iit.it. However we are about to harmonize Q&A also for them.

**Comment by randaz81** [comment]
If a joint does not move at all, even with no power, most likely the corresponding motor is burned or the gearbox is stuck/broken.

**Comment by kt10aan** [comment]
@randaz81, it doesn't sound good :( Is there a way to determine if it is the motor or the gearbox? How can this be fixed?
