### ISSUE TITLE
Increase the saturations for joint torques of CAN robots

### ISSUE THREAD

**Issue by DanielePucci** [robotology/QA#8]
Does anyone know how to increase the saturations of the joint torques for CAN robots?

**Comment by DanielePucci** [comment]
Yes, 
to do this, you have to change two tags' value in two different  configuration files of the robotInterface.

1) Go on the PC104 (e.g. ssh pc104)

2) Open the configuration xml file under .local/share/yarp/robots/iCubGenova0X/hardware/motorControl associated with the part you want to increase the torque saturations of (e.g. icub_torso.xml). Then change the tag "TorqueMax" into the new saturation value, say x.

3) Open the configuration xml file under .local/share/yarp/robots/iCubGenova0X/hardware/VFT associated with the part you want to increase the torque saturations of (e.g. torso_virtual_strain.xml). Then change the tag "fullScale" into the new saturation value, that is x.

**Comment by pattacini** [comment]
:+1:
