### ISSUE TITLE
Changing The texture pattern of the palm in "icubSim" 

### ISSUE THREAD

**Issue by LakshithaHKUST** [robotology/QA#83]
Hello,
Is it possible to change the texture pattern in the right or left palm of the simulator?
To add an arbitrary image from a file?
Thanks

**Comment by pattacini** [comment]
Does anybody have any good clue on this?

**Comment by Tobias-Fischer** [comment]
@martz21 might know

**Comment by LakshithaHKUST** [comment]
Hello Everyone,
I was managed to change the texture pattern titled "bluetexture.bmp" in \iCub\contexts\simConfig\models, and attach an arbitrary image to the palm. That'll do for now
Thanks for the help.
