### ISSUE TITLE
Does complicated environment influence the robot's eye movements in the simulator?

### ISSUE THREAD

**Issue by ZHUQINGPENG** [robotology/QA#87]
Hi, 

I tried to create some real objects in the icub simulator, such as chairs. However, I found that the robot's eye movements will slow down when the number of the objects increases, especially for those complicated objects. Do you know how to solve it?

Walter

**Comment by pattacini** [comment]
Does anyone of @robotology/all-robotology-developers experienced with the simulator have hints on this?
