### ISSUE TITLE
Firmware Problems with robotInterface

### ISSUE THREAD

**Issue by marijnfs** [robotology/QA#89]
While trying to get `robotInteface` start, it started mentioning that the firmware needed to be upgraded. After doing this seemingly successfully, I now get the following errors when starting `robotInterface`: 
[output-firmware.txt](https://github.com/robotology/QA/files/96101/output-firmware.txt)

**Comment by pattacini** [comment]
@marijnfs this is not the right place for such an issue.
Please refer to our [guidelines](https://github.com/robotology/QA/blob/master/CONTRIBUTING.md) and thus open a ticket on [`icub-support`](https://github.com/robotology/icub-support).
